/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : PAC
 #	author : miyako
 #	2018/01/07
 #
 # --------------------------------------------------------------------------------*/

#include "pacparser.h"

// --- PAC
void PAC_FIND_PROXY(sLONG_PTR *pResult, PackagePtr pParams);
